### ISSUE TITLE
I don't see my face in the readme.

### ISSUE THREAD

**Issue by EdsonPaulo** [EufranioDiogo/UCAN-RESOURCES#4]
I don't see my face in the readme as contributor. ahahah
@Creuma-Kuzola  @EufranioDiogo

**Comment by Creuma-Kuzola** [comment]
@EdsonPaulo  O Eufránio esqueceu de adicionar. Mas, já o fiz. Podes confirmar .

**Comment by EdsonPaulo** [comment]
Guud xD :)
